# site settings
title: Welcome
subtitle: by Amit
email: aareddy@umass.edu
description: I am a Computer Science Major<br /> at the University of Massachusetts Amherst.
baseurl: "/AboutMe/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 101 Gajraj Society
city: Kopri, Thane
state: Maharashtra
zip_code: 400603
country: India
phone: (+91) 969-905-8866

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:  https://www.facebook.com/amit.reddy.353/
github_url:  https://github.com/aa-reddy 
instagram_url: https://www.instagram.com/amit__reddy_/
linkedin_url: https://www.linkedin.com/in/amit-reddy-b092a6173/


# build settings
markdown: kramdown

sass:
  style: compressed

theme: jekyll-theme-hacker
